Repository goalajuma/FrondEnd, pull requests merged in 2024-01, with the labels that each got.

#3 refactor: 타입스크립트 초기설정 수정 및 업로드페이지 마이그레이션
  .DS_Store
  package-lock.json
  package.json
  src/components/upload/AddChoice.tsx
  src/components/upload/CategoryNDeadLine.tsx
  src/components/upload/ChoiceOption.tsx
  src/components/upload/FileUpload.tsx
  src/components/upload/Img.tsx
  src/components/upload/Input.tsx
  src/components/upload/Option.tsx
  src/components/upload/PlusBtn.tsx
  src/components/upload/TextArea.tsx
  src/components/upload/UploadButton.tsx
  src/constants/categoryType.ts
  src/routes.ts
  src/utils/AuthAtom.ts
  src/utils/HeaderAtom.ts
  src/utils/SearchAtom.ts
  src/utils/ToastAtom.ts
  src/utils/UploadAtom.ts
  tsconfig.json
Labels: question, 🔄 migration, ✨ refactor

#5 Create pull_request_template.md
  docs/pull_request_template.md
Labels: documentation

#7 refactor: 로그인 컴포넌트 마이그레이션
  .DS_Store
  package-lock.json
  package.json
  src/components/login/Box.tsx
  src/components/login/Button.tsx
  src/components/login/Input.tsx
  src/components/login/InputGroup.tsx
  src/components/login/Label.tsx
  src/components/upload/AddChoice.tsx
  src/components/upload/CategoryNDeadLine.tsx
  src/components/upload/ChoiceOption.tsx
  src/components/upload/FileUpload.tsx
  src/components/upload/Img.tsx
  src/components/upload/Input.tsx
  src/components/upload/Option.tsx
  src/components/upload/PlusBtn.tsx
  src/components/upload/TextArea.tsx
  src/components/upload/UploadButton.tsx
  src/constants/categoryType.ts
  src/hooks/useValid.ts
  src/pages/login/LoginPage.tsx
  src/routes.ts
  src/services/login.ts
  src/styles/Container.tsx
  src/utils/AuthAtom.ts
  src/utils/HeaderAtom.ts
  src/utils/SearchAtom.ts
  src/utils/ToastAtom.ts
  src/utils/UploadAtom.ts
  tsconfig.json
Labels: 🔄 migration

#13 feat: login.ts 마이그레이션
  src/services/Cookie.ts
  src/services/login.ts
Labels: 🔄 migration

#11 Refactor login page
  .DS_Store
  package-lock.json
  package.json
  src/components/login/Box.tsx
  src/components/login/Button.tsx
  src/components/login/Input.tsx
  src/components/login/InputGroup.tsx
  src/components/login/Label.tsx
  src/components/upload/AddChoice.tsx
  src/components/upload/CategoryNDeadLine.tsx
  src/components/upload/ChoiceOption.tsx
  src/components/upload/FileUpload.tsx
  src/components/upload/Img.tsx
  src/components/upload/Input.tsx
  src/components/upload/Option.tsx
  src/components/upload/PlusBtn.tsx
  src/components/upload/TextArea.tsx
  src/components/upload/UploadButton.tsx
  src/constants/categoryType.ts
  src/hooks/useValid.ts
  src/pages/login/LoginPage.tsx
  src/pages/signup/SignUpPage.tsx
  src/routes.ts
  src/services/Cookie.js
  src/services/Cookie.ts
  src/services/index.ts
  src/services/login.ts
  src/services/signup.js
  src/services/signup.ts
  src/styles/Container.tsx
  src/utils/AuthAtom.ts
  src/utils/HeaderAtom.ts
  src/utils/SearchAtom.ts
  src/utils/ToastAtom.ts
  src/utils/UploadAtom.ts
  tsconfig.json
Labels: help wanted, 🔄 migration

#18 refactor: 업로드페이지 마이그레이션 완료
  src/components/upload/AddChoice.tsx
  src/components/upload/ChoiceOption.tsx
  src/components/upload/Img.tsx
  src/components/upload/TextArea.tsx
  src/components/upload/UploadButton.tsx
  src/services/vote.ts
  src/styles/Palette.ts
  src/utils/UploadAtom.ts
Labels: 🔄 migration

#27 hotfix: loginpage 마이그레이션 수정
  src/pages/login/LoginPage.tsx
Labels: bug, 🔄 migration

#34 refactor: mypage 마이그레이션
  src/components/common/modal/Modal.tsx
  src/components/common/modal/Portal.jsx
  src/components/common/modal/Portal.tsx
  src/components/common/mypage/MyPageUl.tsx
  src/components/common/mypage/MypageMainLi.tsx
  src/components/search/SearchInput.tsx
  src/components/search/SearchModal.tsx
  src/pages/login/LoginPage.tsx
  src/pages/my/ProfileModal.tsx
  src/pages/search/SearchPage.tsx
  src/services/my.ts
  tsconfig.json
Labels: 🔄 migration

#35 hotfix: 로그인 에러 수정
  .env.local
  .gitignore
  src/components/common/modal/Modal.tsx
  src/components/common/modal/Portal.jsx
  src/components/common/modal/Portal.tsx
  src/components/common/mypage/MyPageUl.tsx
  src/components/common/mypage/MypageMainLi.tsx
  src/hooks/useValid.ts
  src/pages/my/ProfileModal.tsx
  src/services/my.ts
Labels: fix

#36 fix: 회원가입 페이지 이름 에러 수정
  src/hooks/useValid.ts
Labels: fix

#37 refactor: 마이페이지 마이그레이션 완료
  .env.local
  .gitignore
  public/image/check.png
  src/assets/Loader.tsx
  src/components/common/modal/ModalLayout.tsx
  src/components/common/modal/ModalTemplate.tsx
  src/components/common/mypage/ActiveSign.tsx
  src/components/common/mypage/MyVoteList.tsx
  src/components/common/voteButton/VoteHead.jsx
  src/components/layouts/headers/BackButton.tsx
  src/components/layouts/headers/UploadPageHeader.tsx
  src/components/upload/Anonymous.tsx
  src/components/upload/CategoryNDeadLine.tsx
  src/components/upload/Option.tsx
  src/components/upload/UploadButton.tsx
  src/hooks/useLogin.ts
  src/hooks/useValid.ts
  src/pages/upload/UploadPage.tsx
  src/services/index.ts
  src/services/main.js
  src/services/main.ts
  src/utils/UploadAtom.ts
Labels: 🔄 migration

#38 refact: my page
  src/assets/Loader.tsx
  src/components/common/modal/ModalLayout.tsx
  src/components/common/modal/ModalTemplate.tsx
  src/components/common/mypage/ActiveSign.tsx
  src/components/common/mypage/MyVoteList.tsx
  src/hooks/useLogin.ts
  src/hooks/useValid.ts
  src/services/index.ts
  src/services/main.ts
Labels: 🔄 migration
